name: Release

on:
    release:
        types: published
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
                  registry-url: 'https://registry.npmjs.org'
                  scope: 'yahavi'
            - name: Install
              run: npm i
            - name: Publish
              run: npm publish --access public 
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
